### ISSUE TITLE
Regularly scheduled build failing

### ISSUE THREAD

**Issue by emersonknapp** [ros2/rosbag2_bag_v2#22]
The cron-scheduled action for this package fails

https://github.com/ros2/rosbag2_bag_v2/actions

## Acceptance Criteria
* [ ] Action CI build is green
* [ ] we are building on Ubuntu Focal 20.04

**Comment by Karsten1987** [comment]
https://github.com/ros2/rosbag2/pull/302 broke the compilation I believe.
/cc @mabelzhang 

```
[8.255s] /home/karsten/ros2_ws/install/include/class_loader/meta_object.hpp: In instantiation of ‘B* class_loader::impl::MetaObject<C, B>::create() const [with C = rosbag2_bag_v2_plugins::RosbagV2Storage; B = rosbag2_storage::storage_interfaces::ReadOnlyInterface]’:
[8.255s] /home/karsten/ros2_ws/src/ros2/rosbag2_bag_v2/rosbag2_bag_v2_plugins/src/rosbag2_bag_v2_plugins/storage/rosbag_v2_storage.cpp:193:1:   required from here
[8.256s] /home/karsten/ros2_ws/install/include/class_loader/meta_object.hpp:192:12: error: invalid new-expression of abstract class type ‘rosbag2_bag_v2_plugins::RosbagV2Storage’
[8.256s]      return new C;
[8.256s]             ^~~~~
[8.256s] In file included from /home/karsten/ros2_ws/src/ros2/rosbag2_bag_v2/rosbag2_bag_v2_plugins/src/rosbag2_bag_v2_plugins/storage/rosbag_v2_storage.cpp:15:0:
[8.256s] /home/karsten/ros2_ws/src/ros2/rosbag2_bag_v2/rosbag2_bag_v2_plugins/src/rosbag2_bag_v2_plugins/storage/rosbag_v2_storage.hpp:32:7: note:   because the following virtual functions are pure within ‘rosbag2_bag_v2_plugins::RosbagV2Storage’:
[8.256s]  class RosbagV2Storage : public rosbag2_storage::storage_interfaces::ReadOnlyInterface
[8.256s]        ^~~~~~~~~~~~~~~
[8.256s] In file included from /home/karsten/ros2_ws/src/ros2/rosbag2_bag_v2/rosbag2_bag_v2_plugins/src/rosbag2_bag_v2_plugins/storage/rosbag_v2_storage.hpp:23:0,
[8.257s]                  from /home/karsten/ros2_ws/src/ros2/rosbag2_bag_v2/rosbag2_bag_v2_plugins/src/rosbag2_bag_v2_plugins/storage/rosbag_v2_storage.cpp:15:
[8.257s] /home/karsten/ros2_ws/install/include/rosbag2_storage/storage_interfaces/read_only_interface.hpp:43:16: note: 	virtual void rosbag2_storage::storage_interfaces::ReadOnlyInterface::set_filter(const rosbag2_storage::StorageFilter&)
[8.257s]    virtual void set_filter(const StorageFilter & storage_filter) = 0;
[8.257s]                 ^~~~~~~~~~
[8.257s] /home/karsten/ros2_ws/install/include/rosbag2_storage/storage_interfaces/read_only_interface.hpp:45:16: note: 	virtual void rosbag2_storage::storage_interfaces::ReadOnlyInterface::reset_filter()
[8.257s]    virtual void reset_filter() = 0;
[8.257s]                 ^~~~~~~~~~~~
[8.257s] CMakeFiles/rosbag2_bag_v2_plugins.dir/build.make:114: recipe for target 'CMakeFiles/rosbag2_bag_v2_plugins.dir/src/rosbag2_bag_v2_plugins/storage/rosbag_v2_storage.cpp.o' failed
```

**Comment by mabelzhang** [comment]
#28 should fix the compiler errors

**Comment by clalancette** [comment]
@mabelzhang Is this issue fixed now?  If so, could you close out this issue?

**Comment by mabelzhang** [comment]
Hmm not entirely sure. There were other problems after the compilation errors above were fixed, which might have been fixed too.

@Karsten1987 Do you know?

**Comment by clalancette** [comment]
@hidmic I'm assigning this (old) ticket now because rosbag2_bag_v2 is still failing to build on the buildfarm: https://build.ros2.org/job/Rbin_uF64__rosbag2_bag_v2_plugins__ubuntu_focal_amd64__binary/ .
